version: '3'
services:

 openldap:
   image: jsmitsnl/docker-openldap-postfix-book:latest
   container_name: openldap
   hostname: "openldap.iglu.lu"
   environment:
     LDAP_ORGANISATION: "IGLU"
     LDAP_DOMAIN: "iglu.lu"
     LDAP_BASE_DN: "dc=iglu,dc=lu"
     LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWD:-Tigrou007}"
   volumes:
- ${VOL_LDAP_LIB}:/var/lib/ldap
- ${VOL_SLDAP}:/etc/ldap/slapd.d
- ${VOL_LDAP_CERTS}:/container/service/slapd/assets/certs
    networks:
        maincentral:
            ipv4_address: ${IP_LDAP_HOST}
    dns: ${IP_DNS}
   ports:
     - "389:389"
     - "639:639"

 phpldapadmin:
   image: osixia/phpldapadmin:latest
   container_name: phpldapadmin
   environment:
     PHPLDAPADMIN_LDAP_HOSTS: ${IP_LDAP_HOST}
    networks:
        maincentral:
            ipv4_address: ${IP_PHPLDAPADMIN}
    dns: ${IP_DNS}
   ports:
     - "8443:443"
   depends_on:
     - openldap

dns:
	image: cajetan19/docker-powerdns
	container_name: dns
   hostname: "dns.iglu.lu"
	volumes:
		- ${VOL_DNS_EXT_CONF}:/etc/powerdns
    networks:
        maincentral:
            ipv4_address: ${IP_DNS}
    dns: ${IP_DNS}
	ports:
		- "53":"53"
depends_on:
	- dns-db

dns-db:
   image: postgres
   container_name: dns-db
   hostname: "dns-db.iglu.lu"
   environment:
     POSTGRES_USER: "${DNS_DB_ADMIN_USER:-admin}"
     POSTGRES_PASSWORD: "${DNS_ADMIN_PASSWD:-Tigrou007}"
     PGDATA: "/var/lib/postgresql/data/pgdata"
   volumes:
      - ${VOL_DNS_PGDATA}:/var/lib/postgresql/data/pgdata
      - ${VOL_DNS_CONF}:/etc/postgresql
    networks:
        maincentral:
            ipv4_address: ${IP_DNS_DB}
    dns: ${IP_DNS}
   ports:
     - "8432:5432"
   restart: unless-stopped

 pgadmin4:
   image: fenglc/pgadmin4
   environment:
     DEFAULT_USER: "${PGADMIN_ADMIN_USER:-admin}"
     DEFAULT_PASSWORD: "${PGADMIN_ADMIN_USER:-Tigrou007}"
networks:
        maincentral:
            ipv4_address: ${IP_DB_PGADMIN}
    dns: ${IP_DNS}
   ports:
     - "8080:5050"
   restart: unless-stopped

mail-central:
 image: tvial/docker-mailserver:latest
 environment:
   DMS_DEBUG: 0
   ENABLE_CLAMAV: 1
   ONE_DIR: 1
   ENABLE_POP3: 1
   ENABLE_FAIL2BAN: 0
   ENABLE_MANAGESIEVE: 0
   OVERRIDE_HOSTNAME: "mail.iglu.lu"
   POSTMASTER_ADDRESS: "postmaster@iglu.lu"
   POSTSCREEN_ACTION: "enforce"
   SPOOF_PROTECTION: 1
   ENABLE_SRS: 0
   ENABLE_SPAMASSASSIN: 1
   ENABLE_LDAP: 1
   LDAP_SERVER_HOST: ${IP_LDAP_HOST}
   LDAP_SEARCH_BASE: "ou=users,dc=iglu,dc=lu"
   LDAP_BIND_DN: "cn=admin,dc=iglu,dc=lu"
   LDAP_BIND_PW: "${LDAP_ADMIN_PASSWD:-Tigrou007}"
   ENABLE_POSTGREY: 1
   ENABLE_SASLAUTHD: 1
   SASLAUTHD_MECHANISMS: "ldap"
   SASLAUTHD_LDAP_SERVER: ${IP_LDAP_HOST}
   SASLAUTHD_LDAP_SSL: 0
   SASLAUTHD_LDAP_BIND_DN: "cn=admin,dc=iglu,dc=lu"
   SASLAUTHD_LDAP_PASSWORD: "${LDAP_ADMIN_PASSWD:-Tigrou007}"
   SASLAUTHD_LDAP_SEARCH_BASE: "ou=users,dc=iglu,dc=lu"
   SASLAUTHD_LDAP_FILTER: "(&(uid=%U)(objectClass=posixAccount))"
   DOVECOT_PASS_FILTER: "(&(objectClass=posixAccount)(mail=%u))"
   DOVECOT_USER_FILTER: "(&(objectClass=posixAccount)(mail=%u))"
   LDAP_QUERY_FILTER_USER: "(&(mail=%s)(mailEnabled=TRUE))"
   LDAP_QUERY_FILTER_GROUP: "(&(mail=%s)(mailEnabled=TRUE))"
   LDAP_QUERY_FILTER_ALIAS: "(&(mail=%s)(mailEnabled=TRUE))"

 volumes:
   - {$VOL_MAIL_CENTRAL_MAILS}:/var/mail \
   - {$VOL_MAIL_CENTRAL_STATE}:/var/mail-state \
   - {$VOL_MAIL_CENTRAL_CONF}:/tmp/docker-mailserver \
    networks:
        maincentral:
            ipv4_address: ${IP_MAIL}
    dns: ${IP_DNS}
 ports:
   - "25:25"
   - "143:143"
   - "587:587"
   - "993:993"

networks:
  main-central:
    driver: bridge
    name: maincentral
    ipam:
      config:
        - subnet: ${MAIN_NETWORK_SUBNET:-172.20.0.0/24}