version: '3.5'
services:

  mail:
    image: cajetan19/mailserver
    container_name: mail.${PROJECT_NAME}
    hostname: "mail.${PROJECT_NAME}.iglu.lu"
    environment:
      DMS_DEBUG: 0
      ENABLE_CLAMAV: 1
      ONE_DIR: 1
      ENABLE_POP3: 1
      ENABLE_FAIL2BAN: 0
      ENABLE_MANAGESIEVE: 0
      OVERRIDE_HOSTNAME: "mail.${PROJECT_NAME}.iglu.lu"
      POSTMASTER_ADDRESS: "postmaster@${PROJECT_NAME}.iglu.lu"
      POSTSCREEN_ACTION: "enforce"
      SPOOF_PROTECTION: 1
      ENABLE_SRS: 0
      ENABLE_SPAMASSASSIN: 1
      ENABLE_LDAP: 1
      LDAP_SERVER_HOST: ${IP_LDAP_HOST}
      LDAP_SEARCH_BASE: "ou=users,dc=iglu,dc=lu"
      LDAP_BIND_DN: "${LDAP_ADMIN_DN:-cd=admin,dc=iglu,dc=lu}"
      LDAP_BIND_PW: "${LDAP_ADMIN_PASSWD:-Tigrou007}"
      ENABLE_POSTGREY: 1
      ENABLE_SASLAUTHD: 1
      SASLAUTHD_MECHANISMS: "ldap"
      SASLAUTHD_LDAP_SERVER: ${IP_LDAP_HOST}
      SASLAUTHD_LDAP_SSL: 0
      SASLAUTHD_LDAP_BIND_DN: "${LDAP_ADMIN_DN:-cd=admin,dc=iglu,dc=lu}"
      SASLAUTHD_LDAP_PASSWORD: "${LDAP_ADMIN_PASSWD:-Tigrou007}"
      SASLAUTHD_LDAP_SEARCH_BASE: "ou=users,dc=iglu,dc=lu"
      SASLAUTHD_LDAP_FILTER: "(&(uid=%n)(objectClass=posixAccount)(memberof=CN=${PROJECT_NAME}Mails,ou=groups,DC=iglu,DC=lu))"
      DOVECOT_PASS_FILTER: "(&(objectClass=posixAccount)(uid=%n))"
      DOVECOT_USER_FILTER: "(&(objectClass=posixAccount)(uid=%n))"
      LDAP_QUERY_FILTER_USER: "(&(uid=%u)(mailEnabled=TRUE))"
      LDAP_QUERY_FILTER_GROUP: "(&(uid=%u)(mailEnabled=TRUE))"
      LDAP_QUERY_FILTER_ALIAS: "(&(uid=%u)(mailEnabled=TRUE))"
    volumes:
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_MAIL_MAILS}:/var/mail
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_MAIL_STATE}:/var/mail-state
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_MAIL_CONF}:/tmp/docker-mailserver
    networks:
      main-central: {}
      project-network:
        ipv4_address: ${IP_MAIL}
    dns: ${IP_DNS}
    ports:
      - "${PUBLIC_IP}:25:25"
      - "${PUBLIC_IP}:143:143"
      - "${PUBLIC_IP}:587:587"
      - "${PUBLIC_IP}:993:993"
    restart: unless-stopped

  roundcube:
    container_name: webmail.${PROJECT_NAME}
    hostname: "webmail.${PROJECT_NAME}.iglu.lu"
    image: roundcube/roundcubemail
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: ${IP_MAIL}
      ROUNDCUBEMAIL_SMTP_SERVER: ${IP_MAIL}
      ROUNDCUBEMAIL_SMTP_PORT: 25
      ROUNDCUBEMAIL_PLUGINS: "openssl"
    volumes:
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_ROUNDCUBE}:/var/roundcube/config/ 
    networks:
      project-network:
        ipv4_address: ${IP_WEBMAIL}
    dns: ${IP_DNS}
    ports:
      - "${PUBLIC_IP}:${ROUNDCUBE_PORT}:80"
    depends_on:
      - mail
    restart: unless-stopped      

  samba:
    image: cajetan19/samba-ldap
    container_name: files.${PROJECT_NAME}
    hostname: "files.${PROJECT_NAME}.iglu.lu"
    environment:
      SMB_USER: ${SMB_PROJECT_USER}    
      SMB_USER_PASSWD: ${SMB_PROJECT_USER_PASSWD}
      SMB_EXT_USER: ${SMB_EXTERNAL_USER}    
      SMB_EXT_USER_PASSWD: ${SMB_EXTERNAL_USER_PASSWD}
    volumes:
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_SAMBA_CONF}:/etc/samba
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_SAMBA_SHARE}:/share
    networks:
      project-network:
        ipv4_address: ${IP_SAMBA}
    dns: ${IP_DNS}
    ports:
      - "${PUBLIC_IP}:139:139"
      - "${PUBLIC_IP}:445:445"
    restart: unless-stopped

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab.${PROJECT_NAME}
    hostname: "gitlab.${PROJECT_NAME}.iglu.lu"
    volumes:
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_GITLAB_CONFIG}:/etc/gitlab
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_GITLAB_LOGS}:/var/log/gitlab
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_GITLAB_DATA}:/var/opt/gitlab
    networks:
      main-central: {}
      project-network:
        ipv4_address: ${IP_GITLAB}
    dns: ${IP_DNS}
    ports:
      - "${PUBLIC_IP}:${GITLAB_PORT}:80"
      - "${PUBLIC_IP}:${GITLAB_PORT_SSL}:443"
      - "${PUBLIC_IP}:${GITLAB_PORT_SSH}:22"
    restart: unless-stopped

  wordpress_db:
    container_name: wordpress_db.${PROJECT_NAME}
    image: mysql:5.7
    volumes:
      - ${VOL_WORDPRESS_DB}:/var/lib/mysql
    restart: always
    ports:
      - "${PUBLIC_IP}:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWD}
    networks:
     project-network:
       ipv4_address: ${IP_WORDPRESS_DB}
    dns: ${IP_DNS}
  
  wordpress:
    container_name: wordpress.${PROJECT_NAME}
    depends_on:
      - wordpress_db
    image: dalareo/wordpress-ldap
    ports:
      - "${PUBLIC_IP}:${WORDPRESS_PORT}:80"
    restart: unless-stopped
    volumes:
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_WORDPRESS_CODE}:/var/log/apache2
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_WORDPRESS_HTML}:/var/www/html
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_WORDPRESS_ETC}:/etc/apache2/sites-enabled/
    environment:
      WORDPRESS_DB_HOST: ${IP_WORDPRESS_DB}:3306
      #WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWD}
    networks:
     main-central: {}
     project-network:
       ipv4_address: ${IP_WORDPRESS}
    dns: ${IP_DNS}    
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wpphpmyadmin.${PROJECT_NAME}
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_USER_PASSWD}
        PMA_HOST: ${IP_WORDPRESS_DB}
        PMA_PORT: 3306
    depends_on:
      - wordpress_db
    networks:
      project-network:
        ipv4_address: ${IP_DB_PGADMIN}
    dns: ${IP_DNS}
    ports:
      - "${PUBLIC_IP}:${PHPMYADMIN_PORT}:80"
    restart: unless-stopped
  
  web:
    image: httpd
    container_name: httpd.${PROJECT_NAME}
    ports:
      - "${PUBLIC_IP}:${WEB_PORT}:80"
    volumes:
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_HTTPD_HTDOCS}:/var/www
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_HTTPD_CONF}:/local/apache2/conf
      - ${BASE_VOL}/${PROJECT_NAME}${VOL_HTTPD_LOGS}:/var/log/apache2
    networks:
      project-network:
        ipv4_address: ${IP_HTTPD}
    dns: ${IP_DNS}    

networks:
  main-central:
    external:
      name: main-network
  project-network:
    driver: bridge
    name: ${PROJECT_NAME}
    ipam:
      config:
        - subnet: ${PROJECT_NETWORK_SUBNET}
